FROM node:21
LABEL maintainer="thesatemail@gmail.com"  
WORKDIR /var/www/app/server

ARG ENVIRONMENT
ARG PORT
ARG DB_LOCAL
ARG DB_DEV
ARG DB_PROD
ARG DB_LOCAL_USER
ARG DB_DEV_USER
ARG DB_PROD_USER
ARG DB_LOCAL_PASS
ARG DB_DEV_PASS
ARG DB_PROD_PASS
ARG EMAIL_USER_ICLOUD
ARG EMAIL_SPECIFIC_PASSWORD_ICLOUD
ARG EMAIL_USER
ARG EMAIL_SPECIFIC_PASSWORD
ARG YANDEX_API
ARG YANDEX_KEY

COPY package.json /var/www/app/server
COPY tsconfig.json /var/www/app/server
ENV ENVIRONMENT=$ENVIRONMENT PORT=$PORT DB_LOCAL=$DB_LOCAL DB_DEV=$DB_DEV DB_PROD=$DB_PROD DB_LOCAL_USER=$DB_LOCAL_USER DB_DEV_USER=$DB_DEV_USER DB_PROD_USER=$DB_PROD_USER DB_LOCAL_PASS=$DB_LOCAL_PASS DB_DEV_PASS=$DB_DEV_PASS DB_PROD_PASS=$DB_PROD_PASS EMAIL_USER_ICLOUD=$EMAIL_USER_ICLOUD EMAIL_SPECIFIC_PASSWORD_ICLOUD=$EMAIL_SPECIFIC_PASSWORD_ICLOUD EMAIL_USER=$EMAIL_USER EMAIL_SPECIFIC_PASSWORD=$EMAIL_SPECIFIC_PASSWORD YANDEX_API=$YANDEX_API YANDEX_KEY=$YANDEX_KEY

RUN apt-get update
RUN apt-get install -y poppler-utils
RUN npm install

COPY . /var/www/app/server
RUN npm run build

RUN rm -rf src/

EXPOSE $PORT
CMD ["npm", "start"]